### ISSUE TITLE
Hi how can i test/setup Ramses running in my system 

### ISSUE THREAD

**Issue by tws0002** [RxLaboratory/Ramses#52]
Hi 

how can i test/setup Ramses running in my system?

Thanks 
Desmond

**Comment by Nico-Duduf** [comment]
Hi, I'll have to write a bit of documentation, but we're still in a very early phase of the development.

Short story, this is what you need:

- A webserver running PHP, like Apache
- A mySQL Database (it should work with other SQL databases with minor changes in the PHP code)
- A build of the client, using Qt>=5.5 and any compiler, it should work on all desktop platforms

To use it locally instead of running a real webserver, you can install something like WAMP on Windows

To install:
- Import the SQL file in the mySQL database
https://github.com/Rainbox-dev/Ramses/blob/master/REST%20server/sql/ram.sql
- Copy the PHP files from this folder on the PHP server, and edit config.php with your configuration
- And finally, build and run the client.

If all of this is gibberish for you, it means it's a bit too early in the development to test it ;) Else, feel free to ask for help if you need (but I'll be moving a lot in august and may be a bit long to answer)

We're going to build an installation package soon, with a proper documentation, and start an alpha test. Stay in touch :)

**Comment by tws0002** [comment]
Thanks for the advice. 
I don't have any experience on PHP but I will give it a try!! 
is this pipeline work for after effect only?

**Comment by Nico-Duduf** [comment]
No, it's meant for any motion pictures production ;)

**Comment by tws0002** [comment]
Great Thanks for share with us
